# Generated by Django 4.2.1 on 2023-09-19 12:14

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import feel_the_time.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_activity', models.CharField(max_length=17, null=True)),
                ('time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('comment', models.CharField(max_length=50, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_button_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=feel_the_time.models.default_button_set, null=True, size=None)),
                ('actual_rank_set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=feel_the_time.models.default_rank_set, null=True, size=None)),
                ('all_personal_buttons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=feel_the_time.models.default_button_set, null=True, size=None)),
                ('all_personal_ranks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=feel_the_time.models.default_rank_set, null=True, size=None)),
                ('settings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=feel_the_time.models.default_rank_set, null=True, size=None)),
                ('user_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
