# Generated by Django 4.2.1 on 2023-08-05 16:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30, null=True)),
                ('activity_rank', models.CharField(max_length=30, null=True)),
                ('total_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('current_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feel_the_time.activities')),
            ],
        ),
    ]
