# Generated by Django 4.2.1 on 2023-08-29 06:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feel_the_time', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='button_set',
            new_name='actual_rank_set',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='rank_set',
            new_name='all_personal_buttons',
        ),
        migrations.AddField(
            model_name='person',
            name='actual_button_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['Работа', 'Семья', 'Готовить', 'Спорт', 'В пути', 'Ванна', 'Отдых', 'Есть, пить', 'Уборка', 'Сон'], null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='all_personal_ranks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
