# Generated by Django 4.2.1 on 2023-07-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='activity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
