# Generated by Django 4.2.1 on 2023-08-29 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0002_rename_button_set_person_actual_rank_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='actual_button_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
