# Generated by Django 4.2.1 on 2023-08-15 13:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0002_buttons_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buttons',
        ),
        migrations.AddField(
            model_name='person',
            name='button_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='rank_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='user_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_rank',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feel_the_time.person'),
        ),
    ]
