# Generated by Django 4.2.1 on 2023-07-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0002_time_activity_alter_time_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
