# Generated by Django 4.2.1 on 2023-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0003_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='duration',
            field=models.DateTimeField(null=True),
        ),
    ]
