# Generated by Django 4.2.1 on 2023-08-29 07:14

import django.contrib.postgres.fields
from django.db import migrations, models
import feel_the_time.models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0003_alter_person_actual_button_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='actual_button_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=feel_the_time.models.default_button_set, null=True, size=None),
        ),
    ]
