# Generated by Django 4.2.1 on 2023-08-16 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0003_delete_buttons_person_button_set_person_rank_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='button_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
