# Generated by Django 4.2.1 on 2023-07-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0004_alter_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
