# Generated by Django 4.2.1 on 2023-09-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0006_alter_time_current_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='current_activity',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
