# Generated by Django 4.2.1 on 2023-07-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0013_alter_time_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30, null=True)),
                ('activity_rank', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='time',
            name='activity',
        ),
        migrations.AddField(
            model_name='time',
            name='current_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='feel_the_time.activities'),
        ),
    ]
