# Generated by Django 4.2.1 on 2023-07-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feel_the_time', '0015_activities_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='current_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feel_the_time.activities'),
        ),
    ]
